// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv3sv2vgarz2yEnssNqZXoxxja6bLVjyU',
    appId: '1:706207893729:web:dbefd6e33b7990ff58cfa0',
    messagingSenderId: '706207893729',
    projectId: 'ecom-flutter-cours',
    authDomain: 'ecom-flutter-cours.firebaseapp.com',
    storageBucket: 'ecom-flutter-cours.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNcoyz5TfbNBx4M5tlzU9KnaLwrc2_VB4',
    appId: '1:706207893729:android:958b61fb54c2dc9e58cfa0',
    messagingSenderId: '706207893729',
    projectId: 'ecom-flutter-cours',
    storageBucket: 'ecom-flutter-cours.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tFsnaq0ZoT-n7SLqA77E9FAh6rlb66U',
    appId: '1:706207893729:ios:64f0ae5b7026fac758cfa0',
    messagingSenderId: '706207893729',
    projectId: 'ecom-flutter-cours',
    storageBucket: 'ecom-flutter-cours.appspot.com',
    iosClientId: '706207893729-m0335v5c6482bo36bq69jb9vvgakte83.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tFsnaq0ZoT-n7SLqA77E9FAh6rlb66U',
    appId: '1:706207893729:ios:64f0ae5b7026fac758cfa0',
    messagingSenderId: '706207893729',
    projectId: 'ecom-flutter-cours',
    storageBucket: 'ecom-flutter-cours.appspot.com',
    iosClientId: '706207893729-m0335v5c6482bo36bq69jb9vvgakte83.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
